// Code generated by tygo. DO NOT EDIT.

//////////
// source: ingestion.go

export interface CSVTimeSeriesFile {
  Path: string;
  DateColumnName: string;
  ValueColumnName: string;
  DateLayout: string;
}
export interface InitialSeries {
  Series: Series;
  CSVTimeSeriesFile: CSVTimeSeriesFile;
}

//////////
// source: models.go
/*
Package models defines data models + db integration for backend
*/

export interface Series {
  Model: any /* gorm.Model */;
  title: string;
  description: string;
  unit: string;
  source: string;
  frequency: string;
  notes: string;
  observations: Observation[];
}
export interface Observation {
  Model: any /* gorm.Model */;
  series_id: number /* uint */;
  date: any /* time.Time */;
  value: number /* float64 */;
}
export interface SeriesObservationsAPIResponse {
  series: Series;
  observations: Observation[];
}
